In [1]:
import torch
import torch.nn as nn


In [2]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn((5,3),requires_grad=True)
b = torch.randn(3,requires_grad=True)
z = torch.matmul(x,w)+b
# 预测和真实值之间进行计算loss
loss =  nn.functional.binary_cross_entropy_with_logits(z,y)

In [3]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000019768498AC0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000019768498F10>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1673, 0.0211, 0.1228],
        [0.1673, 0.0211, 0.1228],
        [0.1673, 0.0211, 0.1228],
        [0.1673, 0.0211, 0.1228],
        [0.1673, 0.0211, 0.1228]])
tensor([0.1673, 0.0211, 0.1228])


pytorch会自动的保存一些tensor，以便在反向求导的时候进行计算

In [8]:
x = torch.randn(5,requires_grad=True)
y = x.pow(2)

print(x.equal(y.grad_fn._saved_self))
print(x is y.grad_fn._saved_self)

True
True


并不是所有的梯度中保存的值和输入有关，要看求导之后的东西。

# 对于不可微分的函数的梯度
对于relu，在0点是不可导的，因此，需要进行定义

禁用梯度计算，有多种方式，如no-grad或者inference mode，细粒度的控制可以使用required_grad=false 等。
其中。nn.Module.eval()并不禁用梯度的计算。

required_grad_也可以应用到module，这样整个module下面的所有的参数都是具有梯度计算的。

In [4]:
import torch
X = torch.ones(5,requires_grad=True)
y = sum(X.pow(2))

# autograd可以直接计算在X处输入的地方的对X的导数值
res = torch.autograd.grad(y,X)
print(res)

(tensor([2., 2., 2., 2., 2.]),)
